version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HackForHumanity"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w0scr9zffg37"
s3_prefix = "HackForHumanity"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
